# Generated by Django 2.2.1 on 2019-05-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CityChecking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Users',
        ),
    ]
