# Generated by Django 2.2.1 on 2019-05-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityChecking', '0002_auto_20190529_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'communes',
            },
        ),
    ]
